server:
  port: 0

spring:
  application:
    name: user-service

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
#      username: sa
#      password: 1234


eureka:
  instance:
#    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost #if your os is window, you must need this option
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka


greeting:
  message: Welcome to the Yurim's Simple E-commerce.


logging:
  level:
    com.example.userservice.client: DEBUG

#actuator
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh #refresh config registered in spring-cloud-config using actuator refresh

#token:
#  expiration_time: 86400000 # 60*60*24*1000 하루
#  secret: yurim-token
